# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and run tests"
  lane :ci do
    scan(
      scheme: "DiscoverHub",
      device: "iPhone 15",
      clean: true
    )
  end
  
  lane :archive_only do
  gym(
    scheme: "DiscoverHub",
    project: "DiscoverHub.xcodeproj",
    configuration: "Release",
    clean: true,
    skip_package_ipa: true,
    archive_path: "build/DiscoverHub.xcarchive"
  )
  end

end

